# Pull the base image
FROM node:18.16.0-alpine

# Set working directory
WORKDIR /usr/app

# Copy package.json and package-lock.json
COPY ./package*.json ./

# Install dependencies
RUN npm install

# Copy all files
COPY . .

# Expose port 5173
EXPOSE 5173

# Run npm run dev
CMD ["npm", "run", "dev"]
